SET @r = 0;

SELECT TRUNCATE(AVG(LAT_N), 4)
FROM (SELECT (@r := @r + 1) AS r, LAT_N FROM STATION ORDER BY LAT_N) Temp
WHERE
    r = (SELECT CEIL(COUNT(*) / 2) FROM STATION) OR
    r = (SELECT FLOOR((COUNT(*) / 2) + 1) FROM STATION)
