SELECT CITY, CHAR_LENGTH(CITY) FROM
    (
        SELECT * FROM STATION
        ORDER BY CHAR_LENGTH(CITY) ASC, CITY ASC
        LIMIT 1
    ) AS A
UNION
SELECT CITY, CHAR_LENGTH(CITY) FROM
    (
        SELECT * FROM STATION
        ORDER BY CHAR_LENGTH(CITY) DESC, CITY ASC
        LIMIT 1
    ) AS B
